//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACMAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ErrorList
    {
        public int ID { get; set; }
        public string MESSAGEUID { get; set; }
        public string ERRORMESSAGE { get; set; }
        public System.DateTime ERRORDATE { get; set; }
        public string EMAILTITLE { get; set; }
    }
}
