//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACMAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Sensor_Data
    {
        public int Location { get; set; }
        public System.DateTime Timestamp { get; set; }
        public double SHTTemp { get; set; }
        public double SHTRH { get; set; }
        public double Corr1 { get; set; }
        public double Corr2 { get; set; }
        public double TOW { get; set; }
        public double TC1 { get; set; }
        public double TC2 { get; set; }
        public double TC2Cold { get; set; }
        public double ResistanceReference { get; set; }
        public double Battery { get; set; }
        public bool Rain { get; set; }
    
        public virtual t_Location t_Location { get; set; }
    }
}
